import "./globals.css";

import SupabaseProvider from "./supabase-provider";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SupabaseProvider>
        <body className="bg-neutral-950 w-screen min-h-screen text-white">
          <Navbar />
          {children}
        </body>
      </SupabaseProvider>
    </html>
  );
}
